items: 
- command: org.apache.zookeeper.server.quorum.QuorumPeerMain
  args:
  - C:\bin\kafka_2.11-1.0.0\config\zookeeper.properties
- command: kafka.Kafka
  args:
  - C:\bin\kafka_2.11-1.0.0\config\server.properties
  