name: CI
on:
  push:
    branches:
    - '**'
permissions:
  contents: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7
    - name: Set up JDK 17
      uses: actions/setup-java@v4.1.0
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3.5.0
    - name: Run Gradle checks
      run: ./gradlew check
    - name: Upload reports
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4.3.4
      with:
        name: reports
        path: '**/build/reports/**/*'
  native-image:
    needs: build
    name: ${{ matrix.os }} native image
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up GraalVM JDK
        uses: graalvm/setup-graalvm@v1.2.2
        with:
          java-version: '17'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.5.0
      - name: Compile
        run: ./gradlew nativeCompile -xcheck
      - name: Upload binary
        uses: actions/upload-artifact@v4.3.4
        with:
          name: lunch-scalecube-${{ matrix.os }}
          path: 'lunch-scalecube/build/native/nativeCompile/lunch-scalecube*'
